fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app_editeur:
    resource: "@EditeurBundle/Controller/"
    type:     annotation
    prefix:   /

app_web:
    resource: "@AppBundle/Controller/Site"
    type:     annotation

app_stats:
    resource: "@AppBundle/Controller/Stats"
    type:     annotation

app_api:
    resource: "@AppBundle/Controller/Api"
    type:     annotation
